//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP218458.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.compra = new HashSet<compra>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "no puede estar vacio")]
        [StringLength(10, MinimumLength = 2, ErrorMessage = "debe ser minimo 3 y maximo 10 caracteres")]
        public string nombre { get; set; }

        [Required]
        public string apellido { get; set; }

        [Required]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "No tiene formato de email")]
        public string email { get; set; }

        [Required]
        public string password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<compra> compra { get; set; }
    }
}
